name: Despierta Streamlit
on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Ping App Web
        run: curl -I https://miaa-sincronizador-version-web.streamlit.app

      - name: Ping App Movil
        run: curl -I https://miaa-sincronizador-ver-app.streamlit.app
